loadstring(game:HttpGet("https://raw.githubusercontent.com/Zoprever/RLibrarys/refs/heads/main/Zorex/ZorexUI.lua"))()
local ScreenGui = SearchForUI("ZorexUI")
local IB = Instance.new("ImageButton")
IB.Size = UDim2.new(0, 50, 0, 50)
IB.BackgroundColor3 = Color3.fromRGB(0, 0, 0)
IB.Image = getcustomasset("ZorexSystem/Assets/Execute.png")
IB.Parent = ScreenGui.Window
local UC = Instance.new("UICorner")
UC.CornerRadius = UDim.new(1, 0)
UC.Parent = IB
local TB = Instance.new("TextBox")
TB.Size = UDim2.new(0, 370, 0, 50)
TB.Position = UDim2.new(0, 25, 0, 75)
TB.BackgroundTransparency = 0.5
TB.Parent = ScreenGui.Window
local TB2 = Instance.new("TextBox")
TB2.Size = UDim2.new(0, 370, 0, 50)
TB2.Position = UDim2.new(0, 25, 0, 130)
TB2.BackgroundTransparency = 0.5
TB2.Parent = ScreenGui.Window
local TB3 = Instance.new("TextBox")
TB3.Size = UDim2.new(0, 370, 0, 50)
TB3.Position = UDim2.new(0, 25, 0, 185)
TB3.BackgroundTransparency = 0.5
TB3.Parent = ScreenGui.Window
